version: "3.7"
services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app:delegated

  web:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app:delegated

  db:
    image: "postgres:13"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ranonkeltje
      POSTGRES_USER: ranonkeltje
      POSTGRES_DB: anderwijs_cms
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data:
