version: "3.7"
services:
  cms:
    build:
      context: cms
      target: dev
    env_file:
      - ./cms/.env
    volumes:
      - ./cms/:/app:delegated

  web-cms:
    image: nginx:stable-alpine
    volumes:
      - ./cms/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cms/:/app:delegated
    ports:
    - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anderwijs-cms.rule=Host(`cms.anderwijs.local`)"
      - "traefik.http.routers.anderwijs-cms.tls=false"
      - "traefik.http.routers.anderwijs-cms.entrypoints=web"
      - "traefik.http.services.anderwijs-cms.loadbalancer.server.port=80"

  db:
    image: "postgres:13"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ranonkeltje
      POSTGRES_USER: ranonkeltje
      POSTGRES_DB: anderwijs_cms
    volumes:
      - db_data:/var/lib/postgresql
volumes:
  db_data:

networks:
  default:
    name: anderwijs
    driver: bridge
