enableVersioning: true
handle: footer
name: Footer
propagationMethod: all
siteSettings:
  47340649-8bf4-4792-9f07-6f7fc18bff55:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
