field: da785aaa-db39-4ab7-aafe-a7b9750be686
fieldLayouts:
  646948cf-b4e8-4ced-b869-a70ae6f806b3:
    tabs:
      -
        elements:
          -
            fieldUid: 7dda9a63-7648-4f52-a8a9-ce13c2f4ae6d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 71e62938-1dce-4a49-a016-1c04820d9a70
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  71e62938-1dce-4a49-a016-1c04820d9a70:
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkURL
    instructions: ''
    name: linkURL
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  7dda9a63-7648-4f52-a8a9-ce13c2f4ae6d:
    contentColumnType: text
    fieldGroup: null
    handle: navitemtitle
    instructions: ''
    name: navItemTitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: external
name: external
sortOrder: 2
