field: da785aaa-db39-4ab7-aafe-a7b9750be686
fieldLayouts:
  4c4385e1-5d0e-445b-9739-d25b0458e3d0:
    tabs:
      -
        elements:
          -
            fieldUid: 3063fee0-6270-4c78-b56e-8ee7a24ec4c3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3063fee0-6270-4c78-b56e-8ee7a24ec4c3:
    contentColumnType: string
    fieldGroup: null
    handle: page
    instructions: ''
    name: page
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:f895892f-96de-4c63-bd64-0052e23035c5'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: page
name: page
sortOrder: 1
