field: f39cf5cb-d230-4911-992c-87eb47169ef5
fieldLayouts:
  49393c25-1ddc-48b9-8e41-531b4b2b7839:
    tabs:
      -
        elements:
          -
            fieldUid: b6fb2b00-0abb-4bcb-b89c-243492894ba2
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b0eef42a-dfc6-4251-8d15-b1c30bae4196
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b0eef42a-dfc6-4251-8d15-b1c30bae4196:
    contentColumnType: text
    fieldGroup: null
    handle: rowTitle
    instructions: ''
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b6fb2b00-0abb-4bcb-b89c-243492894ba2:
    contentColumnType: string
    fieldGroup: null
    handle: rowDirection
    instructions: ''
    name: Richting
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Horizontal
            -
              - value
              - horizontal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Vertical
            -
              - value
              - vertical
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: row
name: Sectie
sortOrder: 1
