field: f39cf5cb-d230-4911-992c-87eb47169ef5
fieldLayouts:
  31b3922e-b845-4dec-8724-f0caa02b70cc:
    tabs:
      -
        elements:
          -
            fieldUid: c4c389d6-5e74-4259-a151-979f0138faef
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d3998c08-3e4f-433c-a8a0-1c5faa62a7f2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c4c389d6-5e74-4259-a151-979f0138faef:
    contentColumnType: text
    fieldGroup: null
    handle: twitterHandle
    instructions: 'Twitter gebruikersnaam, pagina naam, of wat twitter ook heeft als handle.'
    name: 'twitter Handle'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d3998c08-3e4f-433c-a8a0-1c5faa62a7f2:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: twitterLimit
    instructions: ''
    name: Limiet
    searchable: false
    settings:
      decimals: 0
      defaultValue: '3'
      max: null
      min: '0'
      prefix: ''
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: twitterFeed
name: 'Twitter Feed'
sortOrder: 4
