contentColumnType: string
fieldGroup: c45017aa-f34b-4172-999a-befebd813965
handle: item
instructions: ''
name: item
searchable: false
settings:
  contentTable: '{{%matrixcontent_item}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
