contentColumnType: string
fieldGroup: c45017aa-f34b-4172-999a-befebd813965
handle: navigationitems
instructions: ''
name: Navigatie
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigationitems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
