contentColumnType: string
fieldGroup: c3821049-5636-431c-b1ac-7edf5a190b0f
handle: pageContent
instructions: ''
name: Inhoud
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
