contentColumnType: string
fieldGroup: aa9188d8-383c-4819-a1af-ca7c5f64a717
handle: pageContent
instructions: ''
name: Inhoud
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
