field: 8e6dd344-4212-4db1-889c-44e3237bc3b6
fieldLayouts:
  6e28b16e-3546-4ba5-a2bc-aa1906864a67:
    tabs:
      -
        elements:
          -
            fieldUid: aedbfab4-1515-4136-aca3-095e30a40608
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a86c69e3-7143-4b3d-8b6d-8a44f75242f7
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a86c69e3-7143-4b3d-8b6d-8a44f75242f7:
    contentColumnType: string
    fieldGroup: null
    handle: ctaButtonPage
    instructions: ''
    name: 'Knop pagina'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:f895892f-96de-4c63-bd64-0052e23035c5'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  aedbfab4-1515-4136-aca3-095e30a40608:
    contentColumnType: string(400)
    fieldGroup: null
    handle: ctaButtonTitle
    instructions: ''
    name: 'Knop titel'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 100
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
